services:
  redis:
    image: redis:latest
    container_name: credis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    build: ./postgres
    container_name: cpostgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb

  service2:
    build: ./service2
    container_name: cservice2
    ports:
      - "5000:80"
    depends_on:
      - postgres

  service3:
    build: ./service3
    container_name: cservice3
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    container_name: cfrontend
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: template-pgadmin
    depends_on:
      - postgres
    ports:
      - 6000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  redis_data:
  redis2_data:
